title: Prithvi Nathan
description: MS-PhD student in Electrical Engineering at UIUC

author:
  name: Prithvi Nathan
  email: pnathan2@illinois.edu

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: pmartc36

header_pages:
  - writing.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
